#!/usr/bin/env python
from os import system
import sys

def run_server(args):
    system('java ' +
        '-Djava.library.path="./out/com/udeyrishi/encryptedfileserver/common/tea" ' +
        '-cp ./out/ ' +
        'com.udeyrishi.encryptedfileserver.server.Main ' +
        ' '.join(args))

def run_client(args):
    system('java ' +
        '-Djava.library.path="./out/com/udeyrishi/encryptedfileserver/common/tea" ' +
        '-cp ./out/ ' +
        'com.udeyrishi.encryptedfileserver.client.Main ' +
        ' '.join(args))

def usage(program_name):
    print("Usage: {0} <client/server> <client/server args>".format(program_name))

if __name__ == '__main__':
    if len(sys.argv) < 2:
        usage(sys.argv[0])
    elif sys.argv[1] == 'server':
        run_server(sys.argv[2:])
    elif sys.argv[1] == 'client':
        run_client(sys.argv[2:])
    else:
        usage(sys.argv[0])
