#!/usr/bin/env python

# Copyright 2016 Udey Rishi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from os import system
import sys

OUT_DIR = 'bin'

def run_server(args):
    system('java ' +
        '-Djava.library.path="./{0}/com/udeyrishi/encryptedfileserver/common/tea" '.format(OUT_DIR) +
        '-cp ./{0}/ '.format(OUT_DIR) +
        'com.udeyrishi.encryptedfileserver.server.Main ' +
        ' '.join(args))

def run_client(args):
    system('java ' +
        '-Djava.library.path="./{0}/com/udeyrishi/encryptedfileserver/common/tea" '.format(OUT_DIR) +
        '-cp ./{0}/ '.format(OUT_DIR) +
        'com.udeyrishi.encryptedfileserver.client.Main ' +
        ' '.join(args))

def usage(program_name):
    print("Usage: {0} <client/server> <client/server args>".format(program_name))

if __name__ == '__main__':
    if len(sys.argv) < 2:
        usage(sys.argv[0])
    elif sys.argv[1] == 'server':
        run_server(sys.argv[2:])
    elif sys.argv[1] == 'client':
        run_client(sys.argv[2:])
    else:
        usage(sys.argv[0])
