#!/usr/bin/env python
from os import system

if __name__ == '__main__':
    system('gcc '+
        '-I$JAVA_HOME/include -I$JAVA_HOME/include/darwin ' +
        '-shared -fpic ' +
        '-o out/production/EncryptedFileServer/com/udeyrishi/encryptedfileserver/common/tea/libcom_udeyrishi_encryptedfileserver_common_tea_TEANative.dylib ' +
        'src/com/udeyrishi/encryptedfileserver/common/tea/com_udeyrishi_encryptedfileserver_common_tea_TEANative.c')

    system('java ' +
        '-Djava.library.path="/Users/rishi/Developer/ece422/p2/EncryptedFileServer/out/production/EncryptedFileServer/com/udeyrishi/encryptedfileserver/common/tea" ' +
        '-cp ./out/production/EncryptedFileServer/ ' +
        'com.udeyrishi.encryptedfileserver.server.Main '+
        '8081' +
        ' ~/Developer/ece422/p2/EncryptedFileServer/test_data/keys.txt ' +
        '-root test_data/server_root')