/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_udeyrishi_encryptedfileserver_common_tea_TEANative */

#ifndef _Included_com_udeyrishi_encryptedfileserver_common_tea_TEANative
#define _Included_com_udeyrishi_encryptedfileserver_common_tea_TEANative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_udeyrishi_encryptedfileserver_common_tea_TEANative
 * Method:    encrypt
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_com_udeyrishi_encryptedfileserver_common_tea_TEANative_encrypt
  (JNIEnv *env, jobject obj, jbyteArray data, jlongArray key);

/*
 * Class:     com_udeyrishi_encryptedfileserver_common_tea_TEANative
 * Method:    decrypt
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_com_udeyrishi_encryptedfileserver_common_tea_TEANative_decrypt
  (JNIEnv *env, jobject obj, jbyteArray data, jlongArray key);

#ifdef __cplusplus
}
#endif
#endif
